// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheRush.WebApp.Infrastructure.Database;

namespace TheRush.WebApp.Migrations
{
    [DbContext(typeof(TheRushDatabaseContext))]
    partial class TheRushDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("TheRush.WebApp.Domain.PlayerRushingStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Att")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AttG")
                        .HasColumnType("REAL");

                    b.Property<double>("Avg")
                        .HasColumnType("REAL");

                    b.Property<int>("First")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FirstPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("FortyPlus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lng")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pos")
                        .HasColumnType("TEXT");

                    b.Property<int>("Td")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<int>("TwentyPlus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("YdsG")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PlayerRushingStats");
                });
#pragma warning restore 612, 618
        }
    }
}
